### ISSUE TITLE
Trying to compile on FreeBSD 10.2

### ISSUE THREAD

**Issue by joeshua** [mimicmod/uhub#1]
I am getting this error 
this one Building C object CMakeFiles/mod_auth_sqlite.dir/src/plugins/mod_auth_sqlite.c.o
/usr/home/dchub/uhub/src/plugins/mod_auth_sqlite.c:22:10: fatal error:
      'sqlite3.h' file not found
# include <sqlite3.h>

```
     ^
```

1 error generated.
**\* Error code 1

**Comment by mimicmod** [comment]
Install sqlite3 correctly with headers. I am no FreeBSD user, try FreeBSD forums or manual on how to install packages with headers.

**Comment by joeshua** [comment]
Alright I have installed it though will ask in main hub and forums thanks mimic

**Comment by mimicmod** [comment]
Installed clean FreeBSD 10.2 on my VirtualBox, installed sqlite3 with pkg install and everything works, pushed just a fix for PCRE library which was not linked correctly. Are you sure you installed sqlite correctly? Use pkg delete sqlite3 and pkg install sqlite3 to reinstall sqlite. Unfortunatelly cmake does not stop when sqlite is not found, so you may think all dependencies are OK.

**Comment by joeshua** [comment]
Yes it is working now from your git but it gives almost same error janvidar/uhub
Hub works with this error below now 

2016-01-22 21:15:50  ERROR: net_setsockopt, fd=3: Socket operation on non-socket (38)
2016-01-22 21:15:50  ERROR: net_set_nosigpipe, fd=3: Socket operation on non-socket (38)
2016-01-22 21:15:50  ERROR: Unable to open file /etc/uhub/users.conf: No such file or directory
2016-01-22 21:15:50   INFO: Starting uhub/0.5.0, listening on :::1511...
2016-01-22 21:15:50   INFO: Loaded plugin: /usr/lib/uhub/mod_auth_sqlite.so: SQLite authentication plugin, version 1.2.

This is my sqlite3 info which is installed from port

sqlite3-3.10.0
Name           : sqlite3
Version        : 3.10.0
Installed on   : Fri Jan 22 20:24:25 2016
Origin         : databases/sqlite3
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : databases
Licenses       : PD
Maintainer     : pavelivolkov@gmail.com
WWW            : https://www.sqlite.org/
Comment        : SQL database engine in a C library
Options        :
        ARMOR          : off
        DBSTAT         : on
        DIRECT_READ    : off
        EDITLINE       : off
        EXTENSION      : on
        FTS4           : on
        FTS5           : off
        ICU            : off
        JSON1          : off
        LIKENOTBLOB    : off
        MEMMAN         : off
        METADATA       : on
        RBU            : off
        READLINEP      : off
        READLINES      : off
        RTREE          : on
        RTREE_INT      : off
        SECURE_DELETE  : on
        SOUNDEX        : off
        STAT3          : off
        STAT4          : off
        STMT           : off
        STSHELL        : on
        THREADS        : on
        TS0            : off
        TS1            : on
        TS2            : off
        TS3            : off
        UNICODE61      : on
        UNLOCK_NOTIFY  : on
        UPD_DEL_LIMIT  : off
        URI            : on
        URI_AUTHORITY  : off
Shared Libs provided:
        libsqlite3.so.0
Annotations    :
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 2.79MiB

**Comment by mimicmod** [comment]
Commited some changes to CMakeLists.txt and closing this issue. Socket error is off-topic here.
